spring:
  application:
    name: grpc-demo
  grpc:
    client:
      channels:
        helloworld:
          address: 'static://127.0.0.1:9090'
          enableKeepAlive: true
          keepAliveWithoutCalls: true
          negotiationType: plaintext
server:
  port: 8888